spring.output.ansi.enabled=ALWAYS
collector.kafka.producer.properties.bootstrap-servers=localhost:9092
collector.kafka.producer.topics.sensors-events=telemetry.sensors.v1
collector.kafka.producer.topics.hubs-events=telemetry.hubs.v1
grpc.server.port=59091