spring.output.ansi.enabled=ALWAYS
aggregator.kafka.producer.properties.bootstrap-servers=localhost:9092
aggregator.kafka.producer.topics.consumer-subscription=telemetry.sensors.v1
aggregator.kafka.producer.topics.producer-topic=telemetry.snapshots.v1

aggregator.kafka.consumer.properties.bootstrap-servers=localhost:9092
aggregator.kafka.consumer.properties.group-id=telemetry.aggregator
aggregator.kafka.consumer.properties.auto-offset-reset=earliest
aggregator.kafka.consumer.properties.enable-auto-commit=false
aggregator.kafka.consumer.properties.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
aggregator.kafka.consumer.properties.value-deserializer=ru.yandex.practicum.kafka.telemetry.event.deserializer.SensorEventDeserializer
