spring:
  output:
    ansi:
      enabled: ALWAYS

collector:
  kafka:
    producer:
      properties:
        bootstrap-servers: localhost:9092
      topics:
        sensors-events: telemetry.sensors.v1
        hubs-events: telemetry.hubs.v1

grpc:
  server:
    port: 59091